[package]
name = "greeter"
version = "0.0.1"
authors = [ "Laché Melvin", "lache.melvin@gmail.com" ]
edition = "2018"

[lib]
name = "greeter"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
hdk = "0.0.100"
serde = "1"
